//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nomina.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nomina.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno es requerido..
        /// </summary>
        public static string ApellidoMRequired {
            get {
                return ResourceManager.GetString("ApellidoMRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno es requerido..
        /// </summary>
        public static string ApellidoPRequired {
            get {
                return ResourceManager.GetString("ApellidoPRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear Usuario. {0}.
        /// </summary>
        public static string CreateUserError {
            get {
                return ResourceManager.GetString("CreateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deducción de Ahorro es requerido..
        /// </summary>
        public static string DedAhorroRequired {
            get {
                return ResourceManager.GetString("DedAhorroRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deducción de Desayuno es requerido..
        /// </summary>
        public static string DedDesayunoRequired {
            get {
                return ResourceManager.GetString("DedDesayunoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro que quieres eliminar este Usuario?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email es requerido..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deducción de Ingreso Baseo es requerido..
        /// </summary>
        public static string IngresoRequired {
            get {
                return ResourceManager.GetString("IngresoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o Contraseña incorrecta..
        /// </summary>
        public static string LogInError {
            get {
                return ResourceManager.GetString("LogInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Mes es requerido..
        /// </summary>
        public static string MesRequired {
            get {
                return ResourceManager.GetString("MesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deducción de Ahorro.
        /// </summary>
        public static string MsjAhorro {
            get {
                return ResourceManager.GetString("MsjAhorro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string MsjApellidoM {
            get {
                return ResourceManager.GetString("MsjApellidoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string MsjApellidoP {
            get {
                return ResourceManager.GetString("MsjApellidoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depositado.
        /// </summary>
        public static string MsjDepositado {
            get {
                return ResourceManager.GetString("MsjDepositado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deducción Desayuno.
        /// </summary>
        public static string MsjDesayuno {
            get {
                return ResourceManager.GetString("MsjDesayuno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string MsjEmail {
            get {
                return ResourceManager.GetString("MsjEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso Base.
        /// </summary>
        public static string MsjIngreso {
            get {
                return ResourceManager.GetString("MsjIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string MsjMes {
            get {
                return ResourceManager.GetString("MsjMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string MsjNombre {
            get {
                return ResourceManager.GetString("MsjNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string MsjPassword {
            get {
                return ResourceManager.GetString("MsjPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Préstamos.
        /// </summary>
        public static string MsjPrestamo {
            get {
                return ResourceManager.GetString("MsjPrestamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string MsjRole {
            get {
                return ResourceManager.GetString("MsjRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string MsjStatus {
            get {
                return ResourceManager.GetString("MsjStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deducción de Tarjetas.
        /// </summary>
        public static string MsjTarjetas {
            get {
                return ResourceManager.GetString("MsjTarjetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Deducciones.
        /// </summary>
        public static string MsjTotalDed {
            get {
                return ResourceManager.GetString("MsjTotalDed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Percepciones.
        /// </summary>
        public static string MsjTotalPercepciones {
            get {
                return ResourceManager.GetString("MsjTotalPercepciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilizado en tarjetas Gasmart.
        /// </summary>
        public static string MsjUtilizadoTar {
            get {
                return ResourceManager.GetString("MsjUtilizadoTar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre es requerido..
        /// </summary>
        public static string NombreRequired {
            get {
                return ResourceManager.GetString("NombreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña es requerida..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Rol de Usuario es requerido..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
    }
}
